#!/usr/bin/perl

if(@ARGV==0)
{
    print qq{
Usage $0 <client number from zero> 

Runs gdb against a running nomiccoind test process
};
    exit 1;
}

$n = shift @ARGV;

$pid = `cat /tmp/coin-datadir-${n}/pid`;

exec("gdb -ex 'attach $pid'");



