#!/usr/bin/perl

if(@ARGV==0)
{
    print qq{
Usage $0 <client number from zero> <commands...> 

Runs test client with the given commands
};
    exit 1;
}

my $n = shift @ARGV;

my $dirname = `dirname $0`;
chomp $dirname;
$command = "$dirname/../src/nomiccoind-test ".`cat /tmp/coin-datadir-${n}/commandline`." '".join("' '", @ARGV)."'";

print "Running: $command\n";

exec $command;

