TARGET_HEADLESS = nomiccoind
TARGET_HEADLESS_TEST = nomiccoind-test
TARGET_QT = nomiccoin-qt
TARGET_QT_TEST = nomiccoin-qt-test

MAKEFILE = Makefile.unix

QT_MID_SUFFIX = 5

export QT_SELECT=qt5

TESTING=1


include Makefile.default

CXXFLAGS += -fPIE -I/usr/include/db4.8 

ifneq ($(NO_QT),1)
  CXXFLAGS += $(shell pkg-config Qt5Core Qt5Gui Qt5Widgets --cflags)
endif

LIBRARIES_HEADLESS := rt pthread $(LIBRARIES_HEADLESS)
LIBRARIES_QT := rt pthread $(LIBRARIES_QT)

include Makefile.common
